# Membuat secret dengan nama mongodb-secret yang berisi 2 data:
# MONGO_ROOT_USERNAME: digunakan sebagai username ketika login ke mongodb
# MONGO_ROOT_PASSWORD: adalah string yang di encode dengan base64 dari 'supersecretpassword'.

apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
stringData:
  MONGO_ROOT_USERNAME: admin
data:
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==