# Membuat sebuah service k8s dengan nama 'karsajobs-backend' dan memberi label 'app: karsajobs'
# Service bertipe NodePort ini akan menargetkan port 8080 pada pod yang memiliki label 'type: backend'.
# NodePort akan mengalokasikan sebuah port pada node, sehingga bisa mengakses aplikasi secara langsung dengan menggunakan NODEIP:NODEPORT
# NODEIP bisa didapatkan dari minikube ip, sedangkan NODEPORT bisa didapatkan dengan mendeskripsikan service ini dan melihat port-nya

apiVersion: v1
kind: Service
metadata:
  name: karsajobs-backend
  labels:
    app: karsajobs
spec:
  ports:
    - port: 8080
  selector:
    type: backend
  type: NodePort