# Membuat sebuah deployment k8s dengan nama 'karsajobs-ui' dan dua label, yaitu 'app: karsajobs' dan 'type: frontend'
# deployment ini akan membuat pod yang berisi 1 replica dan setiap pod akan memiliki dua label, yaitu 'app: karsajobs' dan 'type: frontend'.

# Label type:frontend akan digunakan sebagai selector di file karsajobs-ui-service.yml.
# deployment ini akan membuat pod yang berada pada container.
# container akan menggunakan image dari 'ghcr.io/hann315/karsajobs-ui:latest' dan akan memiliki nama dengan prefix 'karsajobs-frontend-app', dan
# container akan mengekspos port 8000 ke host (pod) dan akan juga memetakan port 8000 di container.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajobs-ui
  labels:
    app: karsajobs
    type: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      type: frontend
  template:
    metadata:
      labels:
        app: karsajobs
        type: frontend
    spec:
      containers:
        - name: karsajobs-frontend-app
          image: ghcr.io/hann315/karsajobs-ui:latest
          ports:
            - containerPort: 8000